title = "Seung Hoon Kim"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Seung Hoon Kim"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke_socials]
    [params.ananke_socials.linkedin]
      name = "linkedin"
      url = "http://www.linkedin.com/in/seung-hoon-kim"
      color = "#008cff"
    [params.ananke_socials.github]
      name = "github"
      url = "https://github.com/seunghoonkim1"
      color = "#008cff"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 40
